apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-monitor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: service-monitor
  template:
    metadata:
      labels:
        app: service-monitor
    spec:
      containers:
      - name: service-monitor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000