apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-monitor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/YOUR_USERNAME/service-monitor-gitops.git
    targetRevision: HEAD
    path: helm/go-monitor

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true